### PR TITLE
WIP: add OCaml Dockerfile

### PR DESCRIPTION
**Pull request by edoput**
This is a draft for #4 , we are reviewing the packages to install.

### packages

- alcotest
- angstrom
- base
- batteries
- cohttp
- core
- core_kernel
- dune
- fix
- fmt
- js_of_ocaml
- lwt
- menhir
- ounit2
- owl
- ppx_deriving
- re
- react
- reason
- sexplib
- utop
- yojson

### CODE REVIEW

**Comment by murmour** [comment]
Looks good! Mandatory package suggestions: `ocamlbuild`, `cppo`. These are very popular build tools.

Also, the twitter account says "Time to sharpen your numerals!", so let's throw in `zarith`, just in case. :-)

Other suggestions: `atd`, `atdgen`, `ppx_deriving_yojson`, `ppx_sexp_conv`.

**Comment by edoput** [comment]
Very good to know, first timer here using OCaml so I've just thrown together the popular packages from opam

**Comment by edoput** [comment]
Ok, now we got to debug the dune build because this is not fun anymore

[full log](https://pastebin.com/hGT9Le85)

interesting bits

```
#=== ERROR while compiling dune.2.6.1 =========================================#
# context     2.0.7 | linux/x86_64 | ocaml-base-compiler.4.10.0 | git+file:///home/opam/opam-repository
# path        ~/.opam/4.10/.opam-switch/build/dune.2.6.1
# command     ~/.opam/4.10/bin/ocaml bootstrap.ml -j 71
# exit-code   2
# env-file    ~/.opam/log/dune-69-93d75f.env
# output-file ~/.opam/log/dune-69-93d75f.out
### output ###
# ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot unix.cma boot/libs.ml boot/duneboot.ml
# ./.duneboot.exe -j 71
# cd _boot && /home/opam/.opam/4.10/bin/ocamlopt.opt -c -g -no-alias-deps -w -49 -I +threads main__upgrade.mli
# File "bin/upgrade.mli", line 1, characters 19-34:
# Error: Unbound module Cmdliner
# 
```

I see dune vendors some packages but I guess the command options are not what it would expect to find them?

**Comment by murmour** [comment]
Can't confirm this. For me, [it works](https://slexy.org/raw/s20Mc8EvIE?token=8546213ba01f5bd474b11ddd22526e0cbf267b386ee7725d1ae4a17e463b8df7&ts=1594579087).

**Comment by murmour** [comment]
A build took 25 minutes on my laptop.

Packages to drop: [bnfgen](https://opam.ocaml.org/packages/bnfgen/) (something obscure), [utop](https://opam.ocaml.org/packages/utop/) (interactive toplevel).

**Comment by murmour** [comment]
Rudi Grinberg (@rgrinberg), the omnipresent demon of Dune, we call thee, the Lord and Leader of build systems and heavenly docker containers (I hope so). For the glory of ICFP Programming Contest 2020, for OCaml (the weapon of humble, but smart), and for Bashkortostan (the superior geopolitical entity), could you please take a look at the compilation error above? Does it look familiar? It happens on `opam install dune` inside a fresh container derived from `ocaml/opam2:4.10`.

**Comment by murmour** [comment]
It suddenly struck me: OCaml is great at producing self-contained binaries, so why spend the effort at reproducible builds, if we can simply push binaries?

@beevee, would that be against rules?

**Comment by beevee** [comment]
@murmour this is not ideal for the performance of our submission system, but it is not against the rules. Just try not to overwhelm us by sending gigabyte-sized submissions every minute!

**Comment by murmour** [comment]
> Just try not to overwhelm us by sending gigabyte-sized submissions every minute!

Nah. Typical OCaml binaries are quite small -- up to several megabytes with the runtime baked in, except if some crazy library is used (which shouldn't be the case in this contest). Building those binaries, on the other hand, can be complicated and slow. Also, git is great at compressing binaries.

Still, a specialized docker image would be of use -- for OCaml novices, and for poor Windows souls.

**Comment by rgrinberg** [comment]
I'm not able to reproduce the issue. Installing dune individually in that image works. Executing the entire build from the docker file also works for me.

**Comment by beevee** [comment]
Is this still a work-in-progress? Is somebody going to finish it before the contest? Do you need any help?

**Comment by murmour** [comment]
@rgrinberg, receive my holy blessing for spending your time! Thanks! :^)

@edoput told me that he and his friend use Podman instead of Docker, so the culprit might be in that. Workaround: use Docker.

@beevee, the image seems good. Could you try building it? This might take some time and requires a few GBs of RAM.

I will prepare a starterkit tomorrow (unless something happens to me).

**Comment by beevee** [comment]
OK, here you go: https://github.com/icfpcontest2020/starterkit-ocaml

I'll merge this PR to test in real conditions.

**Comment by murmour** [comment]
@beevee, `FROM icfpcontest2020/ocaml` doesn't work yet. Did it build?

**Comment by beevee** [comment]
Sadly it didn't:

```
#=== ERROR while installing cryptokit.1.14 ====================================#
opam: "fork" failed: Cannot allocate memory
```

This base image won't build with the default Docker Hub limits (2 GB RAM).

This base image won't build on my local machine (4 GB RAM dedicated to Docker).

How much memory does it take?

**Comment by murmour** [comment]
Around 8GB.

**Pull request merged**
